apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"comments:latest","namespace":"dhbw-exercise-1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"comments\")].image","pause":"false"}]'
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"event-bus"}]'
  labels:
    app: comments
    app.kubernetes.io/component: comments
    app.kubernetes.io/instance: comments
    app.kubernetes.io/part-of: dhbw-exercise-1
    app.openshift.io/runtime: nodejs
  name: comments
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: comments
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: comments
        deploymentconfig: comments
    spec:
      containers:
      - image: replace/me/comments:latest
        imagePullPolicy: Always
        name: comments
        ports:
        - containerPort: 4001
          protocol: TCP
        resources:
          # requests - how much will be guaranteed for the container (impacts scheduling)
          requests:
            memory: "64Mi"
            cpu: "100m"
          # limits - to which extent can the container allocate resources (impacts cgroups limits)
          limits:
            memory: "256Mi"
            cpu: "200m"

        envFrom:
        - configMapRef:
            name: settings

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30